module.exports = {
    PREFS_CACHE_CAMPAIGN: GLOBAL_CONFIG.app.public.name+'_PREFS_CACHE_CAMPAIGN_',
    PREFS_CACHE_HISTORY:GLOBAL_CONFIG.app.public.name+'_PREFS_CACHE_HISTORY_',
    PREFS_CACHE_CAMPAIGN_CATEGORY :GLOBAL_CONFIG.app.public.name+'_PREFS_CACHE_CAMPAIGN_CATEGORY_',
    PREFS_CACHE_CAMPAIGN_UPDATE :GLOBAL_CONFIG.app.public.name+'_PREFS_CACHE_CAMPAIGN_UPDATE_',
    PREFS_CACHE_CAMPAIGN_DONOR:GLOBAL_CONFIG.app.public.name+'+PREFS_CACHE_CAMPAIGN_DONOR_',
};
